### ISSUE TITLE
Change color 

### ISSUE THREAD

**Issue by scramatte** [ZakariaTlilani/nova-nested-tree#3]
Hi,

Can you add a feature to change tag color or at least use primary color?

regards

**Comment by ZakariaTlilani** [comment]
hello,
it does use white in light mode and pale pink in the dark mode which are the default colours of Nova 4, if you've changed your primary colour i'll try to make it possible as soon as possible.

**Comment by scramatte** [comment]
Thank you.
Yes, I'm using another primary color. 
You can use bg-primary-...  instead of fixed color
